model:
  type: APIModel
  # Target Model: Qwen1.5-0.5B-Chat
  model_name: /mnt/shared-storage-user/zhangbo1/models/Qwen/Qwen1.5-7B-Chat
  api_base: http://localhost:21111/v1
  api_key: EMPTY
  concurrency: 4
  mode: chat
  temperature: 0.0
  max_tokens: 512

dataset:
  type: FakeAlignmentDataset
  path: /mnt/shared-storage-user/zhangbo1/Fake-Alignment-main/safety.jsonl

evaluator:
  type: FakeAlignmentEvaluator
  target_batch_size: 4
  judge_batch_size: 4
  judge_model_cfg:
    type: APIModel
    # Judge Model: Qwen1.5-0.5B-Chat (端口 21112)
    model_name: /mnt/shared-storage-user/zhangbo1/models/Qwen/Qwen1.5-7B-Chat
    api_base: http://localhost:21112/v1
    api_key: EMPTY
    concurrency: 4
    mode: chat
    temperature: 0.0
    max_tokens: 64

metrics:
  - type: FakeAlignmentMetric

summarizer:
  type: StandardSummarizer

runner:
  type: LocalRunner
  output_dir: results/fake_alignment_qwen_0.5b
