model:
  type: APIModel
  model_name: gpt-4o
  api_base: http://35.220.164.252:3888/v1
  api_key: OPENAI_API_KEY
  concurrency: 32
  mode: chat
  strip_reasoning: true
  temperature: 0.0
  repetition_penalty: 1.0
  max_tokens: 512

dataset:
  type: MASKDataset
  path: /mnt/shared-storage-user/ai4good1-share/yangjingyi/datasets/cais/MASK

evaluator:
  type: MASKEvaluator
  batch_size: 1
  template_name: mask
  judge_model_cfg:
    type: APIModel
    model_name: gpt-4o # Use same local model for testing
    api_base: http://35.220.164.252:3888/v1
    api_key: OPENAI_API_KEY
    mode: chat
    temperature: 0.0
    max_tokens: 512

metrics:
  - type: MASKMetric

summarizer:
  type: StandardSummarizer

runner:
  type: LocalRunner
  output_dir: results/mask_v01_gpt4o
