model:
  type: APIModel
  model_name: Qwen2.5-VL-7B-Instruct
  api_base: http://100.99.211.178:2001/v1
  api_key: EMPTY
  concurrency: 4
  mode: chat
  temperature: 0.0
  max_tokens: 1024

dataset:
  type: MSSBenchChatDataset
  path: /mnt/shared-storage-user/wuyuyao/safety_bench/mssbench/dataset/combined.json
  image_dir: /mnt/shared-storage-user/wuyuyao/safety_bench/mssbench/dataset/chat
  encode_image_as_base64: true
  # max_samples: 5

evaluator:
  type: MSSBenchEvaluator
  batch_size: 1
  template_name: mssb_chat_if # 生成阶段使用 IF 模板（prompts.py 已注册）
  judge_model_cfg:
    type: APIModel
    model_name: Qwen2.5-VL-7B-Instruct
    api_base: http://100.99.211.178:2001/v1
    api_key: EMPTY
    concurrency: 4
    temperature: 0.0
    max_tokens: 512

metrics:
  - type: MSSBenchMetric

summarizer:
  type: StandardSummarizer

runner:
  type: LocalRunner
  output_dir: /mnt/shared-storage-user/wuyuyao/gitee/Multi-Level-Bionic-Evaluation-Framework-wuyuyao/results/mssbench_chat_qwen2.5-vl-7b